### ISSUE TITLE
Warning in .doLoadActions(where, attach)

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/learn#190]
With R 3.2 on Travis CI I got this warning:

```
Warning message:
In .doLoadActions(where, attach) :
  trying to execute load actions without 'methods' package
```

Following this [post](https://stackoverflow.com/questions/49882495/rscript-warning-message?rq=1) I added `library(methods)` to .travis.yml as follows:

```
matrix:
  include:
  # ... more stuff
  - r: 3.3
  - r: 3.2
    script: Rscript -e 'library(methods)'
```

This fixed the problem
