### ISSUE TITLE
TRAVIS_R_VERSION_STRING to only report coverage for the release version

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/learn#195]
https://github.com/r-lib/devtools/blob/188a6136bce35abc4763887767d687aab0fc57bc/.travis.yml#L25

```
# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
```

Seems like an alternative approach to nesting `after_success` under `release`

```
matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
  - r: # ... more stuff
```
