### ISSUE TITLE
Checklists to create a new package for ForestGEO

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/learn#53]
See blogs:

* [functions-based package](https://fgeo.netlify.com/2018/03/28/2018-03-28-building-infrastructure-for-r-packages-with-usethis/)
* [Data package](https://fgeo.netlify.com/2018/04/04/2018-04-04-building-infrastructure-for-a-data-package/)

**Comment by maurolepore** [comment]
### Website: `_pkgdown.yml`

```yml
template:
  params:
    bootswatch: united



home:
  links:
  - text: Learn more
    href: http://www.forestgeo.si.edu/



reference:
  - title: "xxx Function category"
    desc: >
      xxx Function subcategory
    contents:
      - xxxfunctionname
      - xxxfunctionname

  - title: "xxx Function category"
    desc: >
      xxx Function subcategory
    contents:
      - xxxfunctionname
      - xxxfunctionname

  - title: "xxx Dataset category"
    desc: >
      xxx Dataset subcategory
    contents:
      - xxxdatasetname
      - xxxdatasetname



articles:
  - title: "xxx Tutorial category"
    desc: >
      xxx Tutorial subcategory
    contents:
    - xxxtutorialname

  - title: "xxx Tutorial category"
    desc: >
      xxx Tutorial subcategory
    contents:
    - xxxtutorialname



navbar:
  type: default
  left:
    - text: Functions Index
      href: reference/index.html
    - text: Tutorials
    href: articles/index.html
```
